apiVersion: v1
kind: ConfigMap
metadata:
  name: esxi-host-exporter-config
data:
  config.yaml: |
    port: {{ $.Values.listen_port }}
    ssl_verify: false
    collectors:
      overall_state_collector:
        enabled: true
      critical_service_collector:
        enabled: true
        max_threads: 10
        services:
          - hostd
          - nsx-opsagent
          - nsx-proxy
          - nsxa
          - ntpd
          - vpxa
          - vvold