apiVersion: v1
kind: ConfigMap
metadata:
  name: esxi-host-exporter-config
data:
  config.yaml: |
    port: 9666
    ssl_verify: false
    collectors:
      overall_state_collector:
        enabled: {{ Values.collectors.overall_state_collector.enabled }}
      critical_service_collector:
        enabled: {{ Values.collectors.critical_service_collector.enabled }}
        max_threads: 10
        services:
          - hostd
          - nsx-opsagent
          - nsx-proxy
          - nsxa
          - ntpd
          - vpxa
          - vvold