enabled: false
listen_port: 9666
docker_repo: DEFINED-IN-REGION
image_version: DEFINED-IN-REGION
vcenter_user: DEFINED-IN-REGION
vcenter_password: DEFINED-IN-REGION
esxi_user: DEFINED-IN-REGION
esxi_password: DEFINED-IN-REGION
atlas_configmap: atlas-netbox-sd
alerts:
  enabled: false
  prometheus: DEFINED-IN-REGION
resources:
  limits:
    memory: 10G
    cpu: "1"
  requests:
    memory: 5G
    cpu: 500m